name: Deploy Virtual Lolly Storybook

# Controls when the action will run. Triggers the workflow on push event
# but only for the master branch
on:
  push:
    branch: [master]

jobs:
  # This workflow builds the storybook on a Ubuntu VM and deploys it to Netlify.
  DeployApp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the Repository
        uses: actions/checkout@v2

      - name: Install NodeJS
        uses: actions/setup-node@v2
        with: { node-version: "14.15.0" }

      - name: Install Dependencies
        uses: jaid/action-npm-install@v1.2.1

      - name: Build Storybook
        run: yarn build-storybook

      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v1.1.5
        with:
          publish-dir: "./storybook-static"
          deploy-message: "${{ github.event.head_commit.message }}"
          production-branch: master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
